fieldLayouts:
  8c5a14d3-c459-4853-ac53-9502e4b44cac:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 77d02200-2ac4-48e5-a3ad-cbb9d2cca6ce # Header Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f2f4cbf6-8b9c-45bd-96b3-e34ecd08f313 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3605c850-c69e-420d-9535-8fe03a52adba # Sub Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5c1e17dd-b91e-4c7c-a570-2a1c214c11d1 # Robust Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Header
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 462f0307-2210-420c-8bea-78751c71e4cf # Article Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 761229cb-9c33-42ac-a4d0-8456de91c507
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b6f9734e-6887-4109-8fe5-c5f1cb6f7a4f # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
handle: newsArticles
hasTitleField: false
name: 'News Articles'
section: 5a05ecad-dba8-41b6-8bb3-0ac68748125d # News Articles
sortOrder: 1
titleFormat: '{headline}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
