fieldLayouts:
  93d94529-7997-4bb5-bff7-7876c9455f92:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: a75b7e61-5a89-4ab3-9854-0242124dbe12 # Bio Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e3176b3a-ccd8-4d19-a7da-61519b7af7ad # Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 260d1a8e-e7fa-49d9-8920-d1d3a431a5e6 # Job Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eabcc4b1-fda3-4dfa-b71d-5fd58c7177fb # Email Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ce65c1bb-6032-401d-ba99-ab10a05eb034 # Specialization
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 88ef55c2-f312-4480-be12-ef5e01243d15 # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aab798a5-b0b1-49b9-bc02-e31fa19a4aa5 # Image
            instructions: ''
            label: 'Social Image'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Team Bio'
        sortOrder: 1
handle: team
hasTitleField: true
name: Team
section: d6513807-2d53-4794-a0f5-3c29672441e3 # About
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
