fieldLayouts:
  67fe1ee8-7d5e-4e8a-8f81-a901b6187b4c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: Specializations
name: Specializations
siteSettings:
  988e54bc-f2ef-46d4-b73b-3af77d27754d: # Craft-template
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: d6ac074e-69bd-45df-a8c0-114236410e7b
