baseUrl: $DEFAULT_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: Craft-template
primary: true
siteGroup: 34d58d53-7c87-44b9-ae23-1e9631005bb9 # Craft-template
sortOrder: 1
