childBlocks: ''
field: b6f9734e-6887-4109-8fe5-c5f1cb6f7a4f # Content Builder
fieldLayouts:
  a4a56db2-25c9-48ee-a387-55152ed3cffd:
    tabs:
      -
        elements:
          -
            fieldUid: f2f4cbf6-8b9c-45bd-96b3-e34ecd08f313 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6a667c96-f49d-4aaa-a785-f1cf42368488 # Accordion
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contents
        sortOrder: 1
handle: accordion
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Accordion
sortOrder: 3
topLevel: true
