childBlocks: ''
field: b6f9734e-6887-4109-8fe5-c5f1cb6f7a4f # Content Builder
fieldLayouts:
  c4acadb7-bc4c-406e-90e7-8e10d2161fae:
    tabs:
      -
        elements:
          -
            fieldUid: f2f4cbf6-8b9c-45bd-96b3-e34ecd08f313 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4185f6f7-77c9-4bb1-87bb-46f446875c13 # Carousel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contents
        sortOrder: 1
handle: carousel
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Carousel
sortOrder: 4
topLevel: true
