contentColumnType: string
fieldGroup: 634fac22-3a60-437b-8562-03664b8b4e1c # Content Builder Elements
handle: accordion
instructions: ''
name: Accordion
searchable: true
settings:
  columns:
    __assoc__:
      -
        - 841a86b9-3fea-4af3-8016-16717b16163e # Headline
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 5d0b5431-50d7-477b-be9c-099272f1a2e9 # Contents
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_accordion}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
