contentColumnType: text
fieldGroup: dd11dc8a-c8ec-4ed5-9620-ce9b283cf148 # Company Info
handle: companyName
instructions: 'Enter Company Name'
name: 'Company Name'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Company Name'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
