contentColumnType: text
fieldGroup: 33023d69-c14e-46a9-917c-916d6650938a # Team
handle: jobTitle
instructions: ''
name: 'Job Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
