contentColumnType: text
fieldGroup: 37c3afdd-8944-40bf-a402-6b44f67cc2f8 # Legacy Import
handle: legacyAuthor
instructions: ''
name: 'Legacy Author'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
