contentColumnType: string
fieldGroup: fc9d7853-6187-4c48-9b8c-e9242c8b798a # Common
handle: robustLink
instructions: ''
name: 'Robust Link'
searchable: false
settings:
  contentTable: '{{%stc_robustlink}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
