enableVersioning: true
handle: portfolio
name: Portfolio
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  988e54bc-f2ef-46d4-b73b-3af77d27754d: # Craft-template
    enabledByDefault: true
    hasUrls: true
    template: template/_portfolio/_entry
    uriFormat: portfolio
type: single
