enableVersioning: true
handle: terms
name: Terms
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  988e54bc-f2ef-46d4-b73b-3af77d27754d: # Craft-template
    enabledByDefault: true
    hasUrls: true
    template: template/_terms/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: a9392aa6-fd53-4472-8a53-2de49f57f7d9
type: structure
